apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: webapp
type: Opaque
data:
  DB_PASSWORD: YWRtaW5hZG1pbjE=
  CLERK_SECRET_KEY: c2tfdGVzdF92aExhdmtya2plaWxkTDVSem50UURjc3ZzTm9yejhBaE5YZkVISkxFSFA=