apiVersion: v1
kind: Service
metadata:
  name: backend1-service
  namespace: {{ .Values.backend1.namespace }}
spec:
  selector:
    app: backend1
  ports:
    - protocol: TCP
      port: {{ .Values.backend1.service.env.PORT}}
      targetPort: {{ .Values.backend1.service.env.TARGET_PORT }}
