apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: webapp
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.frontend.labels }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.env.PORT }}
      targetPort: {{ .Values.frontend.service.env.TARGET_PORT }}