apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app
  namespace: {{ .Values.Ingress.namespace }}
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.Ingress.ingressClassName }}
  tls:
  - hosts:
    - {{ .Values.Ingress.hosts }}
    secretName: myapp-tls
  rules:
  - host:  {{ .Values.Ingress.hosts }}
    http:
      paths:
      
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: backend1-service
            port:
              number: {{ .Values.Ingress.users.port }}
      - path: /api/blogs
        pathType: Prefix
        backend:
          service:
            name: backend2-service
            port:
              number: {{ .Values.Ingress.blogs.port }}
      - path: /api/comments
        pathType: Prefix
        backend:
          service:
            name: backend2-service
            port:
              number: {{ .Values.Ingress.blogs.port }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: {{ .Values.Ingress.home.port }}
